### ISSUE TITLE
Latest version 1.5 not longer compatible with python 2.7

### ISSUE THREAD

**Issue by andresp99999** [dashea/requests-file#17]
Hello,

  We just noticed that the most recent version upgrade included a line that is not compatible with Python 2.7. This is a stacktrace of the error when trying to use it from tldextract.

```
>>> 
>>> import tldextract
>>> tldextract.extract('xx.com')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "tldextract/tldextract.py", line 303, in extract
    return TLD_EXTRACTOR(url)
  File "tldextract/tldextract.py", line 183, in __call__
    suffix_index = self._get_tld_extractor().suffix_index(translations)
  File "tldextract/tldextract.py", line 223, in _get_tld_extractor
    raw_suffix_list_data = find_first_response(self.suffix_list_urls)
  File "tldextract/remote.py", line 37, in find_first_response
    session.mount('file://', FileAdapter())
  File "requests_file.py", line 14, in __init__
    super().__init__()
TypeError: super() takes at least 1 argument (0 given)
```

As a quick workaround we created a fork and pushed this change: https://github.com/AirPR/requests-file/commit/d9c580ef250aaf708eb48b48c302a92d7f63dcf6 (this was affecting a prod system).

**Comment by dashea** [comment]
Fixed by https://github.com/dashea/requests-file/pull/18
